let mockRecipes = [
    {
        id: 1,
        name: "MOCK - steak",
        image: "https://img.freepik.com/free-photo/juicy-steak-medium-rare-beef-with-spices-grilled-vegetables_24972-2328.jpg?size=626&ext=jpg&ga=GA1.1.1412446893.1704672000&semt=sph",
        instructions:"Add the oil to the pan and heat until it begins to shimmer and move fluidly around the pan.",
        protein:"steak",
        ingredients:"oil, butter",
        nutrition:"999999 grams protein",
    },
    {
        id: 2,
        name: "MOCK - chicken",
        image: "https://natashaskitchen.com/wp-content/uploads/2022/05/Tuscan-Chicken-Recipe-SQ.jpg",
        instructions: "Put the chicken in the oven",
        protein:"chicken",
        ingredients:"seasonings",
        nutrition:"9999999 grams of protein",
    },
    {
        id: 3,
        name: "MOCK - Salmon",
        image: "https://www.cookingclassy.com/wp-content/uploads/2018/05/grilled-salmon-3.jpg",
        instructions:"cut the salmon into pieces", 
        protein:"salmon",
        ingredients:"salt and pepper",
        nutrition:"999999 grams of protein",
    },
    {
        id: 4,
        name: "MOCK - Pan-Fried Sesame Garlic Tofu",
        image: "https://www.tablefortwoblog.com/wp-content/uploads/2018/09/pan-fried-spicy-garlic-tofu-recipe-photos-tablefortwoblog-1-scaled.jpg.webp",
        instructions:"1. Place two paper towels on a plate then place the entire block of tofu (drained from its packaging liquid) onto the plate. Place two more paper towels on top of the tofu then put a heavy item on top. Not TOO heavy that it would completely crush the tofu but heavy enough that it can squeeze out liquid.2. Leave the tofu to drain for 30 minutes and halfway through, change out the paper towels. 3. ALTERNATIVELY and more eco-friendly: place a wire baking rack on top of a rimmed baking sheet. Place tofu on top and then put a heavy object on top and let drain for 30 minutes. 4. Once the tofu has drained, slice in half then into cubes and place into a large bowl. Sprinkle cornstarch on top and gently toss with your hands to ensure all tofu pieces are covered. 5. In a large skillet, add sesame oil and vegetable oil then bring up to medium-high heat. 6. Once oil is heated up, add the tofu to the skillet and let brown on all sides. 7. In the meantime, whisk together the ingredients for the sauce. 8. Once the tofu has browned and crisped up on all sides, add the sauce to the skillet and it should start to thicken immediately. Toss the tofu around to coat then remove from heat.9. Serve and enjoy!",
        protein:"tofu",
        ingredients:"cornstarch, sesame oil, vegetable oil, low-sodium soy sauce, water, honey, sambal oelek, garlic paste, rice wine vinegar",
        nutrition:"1 SERVING | Calories: 313 KCAL | Carbohydrates: 17 G | Protein: 19 G | Fat: 16 G",
    },
    {
        id: 5,
        name: "MOCK - Egg-celent Breakfast Muffins",
        image: "https://fruitsandveggies.org/wp-content/uploads/2023/11/shutterstock_1445166449-masthead.jpg",
        instructions: "1. Preheat the oven to 350 degrees. Prepare the muffin tin with non-stick spray. 2. Wash your hands with soap and water. 3. Crack the eggs into a large bowl. Then wash your hands with soap and water again. 4. In the large bowl, whisk together the eggs, milk, pepper, and paprika until well combined. 5. Add the broccoli, red bell pepper, orange bell pepper, and cheddar cheese to the bowl. Stir to combine. 6. Using a ¼ cup measure, fill each muffin spot so that it is about ¾ of the way full. 7. Bake for 20 minutes, or until the eggs are set. 8. Allow to cool slightly before using a spatula or butter knife to remove the egg bites from the muffin tin. And enjoy!",
        protein:"Eggs",
        ingredients:"Oil, Milk, Pepper, Praprika, Brocolli, Red Bel Pepper, Orange Bell Pepper, Cheddar Cheese",
        nutrition:"9999999 grams of protein",
    },
    {
        id: 6,
        name: "MOCK - Salmon",
        image: "https://www.cookingclassy.com/wp-content/uploads/2018/05/grilled-salmon-3.jpg",
        instructions:"cut the salmon into pieces", 
        protein:"salmon",
        ingredients:"salt and pepper",
        nutrition:"999999 grams of protein",
    },
    {
        id: 7,
        name: "MOCK - steak",
        image: "https://img.freepik.com/free-photo/juicy-steak-medium-rare-beef-with-spices-grilled-vegetables_24972-2328.jpg?size=626&ext=jpg&ga=GA1.1.1412446893.1704672000&semt=sph",
        instructions:"Add the oil to the pan and heat until it begins to shimmer and move fluidly around the pan.",
        protein:"steak",
        ingredients:"oil, butter",
        nutrition:"999999 grams protein",
    },
    {
        id: 8,
        name: "MOCK - chicken",
        image: "https://natashaskitchen.com/wp-content/uploads/2022/05/Tuscan-Chicken-Recipe-SQ.jpg",
        instructions: "Put the chicken in the oven",
        protein:"chicken",
        ingredients:"seasonings",
        nutrition:"9999999 grams of protein",
    },
    {
        id: 9,
        name: "MOCK - Salmon",
        image: "https://www.cookingclassy.com/wp-content/uploads/2018/05/grilled-salmon-3.jpg",
        instructions:"cut the salmon into pieces", 
        protein:"salmon",
        ingredients:"salt and pepper",
        nutrition:"999999 grams of protein",
    },
]

export default mockRecipes